### PR TITLE
fix go code style

### PR DESCRIPTION
**Pull request by ddkwork**
fix go code style

### CODE REVIEW

**Comment by Splizard** [comment]
You've added some examples using `github.com/AllenDang/giu`, but this uses the Imgui C code directly, not this port. What is the purpose of these examples?

**Comment by ddkwork** [comment]
> You've added some examples using `github.com/AllenDang/giu`, but this uses the Imgui C code directly, not this port. What is the purpose of these examples?
> 

As mentioned in the debugging section of your readme, this is to port more demos and debug use, and the giu demo code will be deleted when the migration is complete

**Comment by Splizard** [comment]
Is the idea to refactor `github.com/AllenDang/giu` and `hexdunk` to use this port of dear imgui ?

**Comment by ddkwork** [comment]
> Is the idea to refactor `github.com/AllenDang/giu` and `hexdunk` to use this port of dear imgui ?

yes

**Comment by Splizard** [comment]
will you reopen the PR?

**Comment by ddkwork** [comment]
> will you reopen the PR?

sure

**Pull request closed without merging**
